# Generated by Django 5.2.7 on 2025-10-14 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวนที่ยืม')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ร้องขอ')),
                ('start_date', models.DateField(verbose_name='วันที่ยืม')),
                ('end_date', models.DateField(verbose_name='วันที่กำหนดคืน')),
                ('status', models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติ'), ('REJECTED', 'ถูกปฏิเสธ'), ('CANCELLED', 'ยกเลิก'), ('RETURNED', 'คืนแล้ว')], default='PENDING', max_length=10, verbose_name='สถานะ')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืม')),
            ],
            options={
                'verbose_name': 'คำขอยืม',
                'verbose_name_plural': 'คำขอยืม',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อของ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='รหัส')),
                ('total_stock', models.IntegerField(default=1, verbose_name='จำนวนรวม')),
            ],
            options={
                'verbose_name': 'สิ่งของ',
                'verbose_name_plural': 'สิ่งของ',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item', verbose_name='สิ่งของที่ยืม'),
        ),
    ]
